# Site settings
title: DEBTRON
tag_text: DEBTRON
description: DEBTRON provides bespoke Hardware as a Service solutions for government administration professionals and freelancing politicians

# Build settings
markdown: kramdown

exclude: ["README.md"]
